# Generated by Django 4.0.3 on 2023-02-15 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island_rank', models.CharField(max_length=4, verbose_name='Island Rank')),
                ('school', models.CharField(max_length=30, verbose_name='School')),
                ('whatsapp_number', models.CharField(max_length=12, verbose_name='Whataspp Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='sample',
        ),
    ]
