# Generated by Django 4.0.3 on 2023-02-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_students_delete_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='island_rank',
            field=models.CharField(blank=True, max_length=4, verbose_name='Island Rank'),
        ),
        migrations.AlterField(
            model_name='students',
            name='school',
            field=models.CharField(blank=True, max_length=30, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='students',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Whataspp Number'),
        ),
    ]
