# Generated by Django 4.0.3 on 2023-02-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_students_island_rank_alter_students_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Is Registered Student'),
        ),
    ]
